<!DOCTYPE html>
<html lang="en"><head>
<script src="embeddings_comparison_slides_files/libs/clipboard/clipboard.min.js"></script>
<script src="embeddings_comparison_slides_files/libs/quarto-html/tabby.min.js"></script>
<script src="embeddings_comparison_slides_files/libs/quarto-html/popper.min.js"></script>
<script src="embeddings_comparison_slides_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="embeddings_comparison_slides_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="embeddings_comparison_slides_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="embeddings_comparison_slides_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.27">

  <meta name="author" content="Carlos Mendez">
  <title>Satellite Embeddings for Public Service Prediction</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="embeddings_comparison_slides_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="embeddings_comparison_slides_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="embeddings_comparison_slides_files/libs/revealjs/dist/theme/quarto-534cd8e3a96973385dffff3f4709048d.css">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="embeddings_comparison_slides_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Satellite Embeddings for Public Service Prediction</h1>
  <p class="subtitle">Comparing Regular vs.&nbsp;Population-Weighted Embeddings</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Carlos Mendez 
</div>
</div>
</div>

</section>
<section class="slide level2">

<style>
/* === COLOR VARIABLES === */
:root {
  --primary-blue: #1E3A8A;
  --secondary-green: #0D9488;
  --accent-orange: #F97316;
  --text-dark: #333333;
  --text-light: #666666;
  --bg-light: #f8f9fa;
}

/* === TYPOGRAPHY HIERARCHY === */
/* Level 1: Main titles - Navy */
h1, h2, .reveal .slide-title {
  color: var(--primary-blue) !important;
  font-weight: bold;
}

/* Level 2: Subtitles - Teal (optional, if h3/h4 used) */
h3, h4 {
  color: var(--secondary-green) !important;
  font-weight: 600;
  margin-top: 1em;
}

/* Level 3: Bold text - Teal (emphasis) */
strong, b, .emphasis {
  color: var(--secondary-green) !important;
  font-weight: bold;
}

/* === TEXT ELEMENTS === */
.reveal {
  color: var(--text-dark);
  line-height: 1.5;
}

.reveal ul, .reveal ol {
  color: var(--text-dark);
}

/* Secondary text */
.text-muted, .subtitle {
  color: var(--text-light);
  font-size: 0.9em;
}

/* === SPECIAL ELEMENTS === */
/* Key findings box */
.key-finding {
  background: var(--bg-light);
  border-left: 4px solid var(--accent-orange);
  padding: 1em;
  margin: 1em 0;
  border-radius: 4px;
}

/* Success/positive callout */
.callout-success {
  background: rgba(13, 148, 136, 0.1);
  border-left: 4px solid var(--secondary-green);
  padding: 1em;
  margin: 1em 0;
  border-radius: 4px;
}

/* Warning/attention callout */
.callout-warning {
  background: rgba(249, 115, 22, 0.1);
  border-left: 4px solid var(--accent-orange);
  padding: 1em;
  margin: 1em 0;
  border-radius: 4px;
}

/* Category badges */
.badge {
  display: inline-block;
  padding: 0.25em 0.6em;
  font-size: 0.85em;
  font-weight: 600;
  border-radius: 12px;
  margin: 0.2em;
}

.badge-primary {
  background: var(--primary-blue);
  color: white;
}

.badge-success {
  background: var(--secondary-green);
  color: white;
}

.badge-warning {
  background: var(--accent-orange);
  color: white;
}

/* === TABLES === */
.reveal table th {
  background: var(--primary-blue);
  color: white;
  font-weight: 600;
}

.reveal table td {
  border-bottom: 1px solid #dee2e6;
}

/* Highlight positive values */
.positive {
  color: var(--secondary-green);
  font-weight: 600;
}

/* Highlight negative/concerning values */
.negative {
  color: var(--accent-orange);
  font-weight: 600;
}

/* === LAYOUT IMPROVEMENTS === */
/* Better column spacing */
.reveal .columns {
  gap: 2em;
}

/* Icon styling */
.icon-success::before { content: "✓"; color: var(--secondary-green); margin-right: 0.5em; }
.icon-warning::before { content: "⚠"; color: var(--accent-orange); margin-right: 0.5em; }
.icon-info::before { content: "ℹ"; color: var(--primary-blue); margin-right: 0.5em; }
</style>
</section>
<section id="research-question" class="slide level2 smaller">
<h2>Research Question</h2>
<p><strong>Can population-weighted satellite embeddings improve public service prediction?</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Two Approaches:</strong></p>
<ol type="1">
<li><strong>Regular Embeddings</strong>
<ul>
<li>Standard satellite image features</li>
<li>Uniform spatial coverage</li>
<li>Treats all areas equally</li>
</ul></li>
<li><strong>Population-Weighted Embeddings</strong>
<ul>
<li>Weighted by population density</li>
<li>Emphasizes where people live</li>
<li>Aligns with service delivery</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>Dataset:</strong></p>
<ul>
<li>339 Bolivian municipalities</li>
<li>20 public service indicators</li>
<li>5 categories: Utilities, Education, Health, Infrastructure, Institutional</li>
<li>64-dimensional embeddings from 2017 satellite imagery</li>
</ul>
<p><strong>Method:</strong></p>
<ul>
<li>Random Forest regression</li>
<li>80/20 train-test split</li>
<li>Same model parameters for fair comparison</li>
</ul>
</div></div>
</section>
<section id="embedding-types-explained" class="slide level2 smaller">
<h2>Embedding Types Explained</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Regular Embeddings:</strong></p>
<ul>
<li>Extract features from satellite images</li>
<li>Each pixel weighted equally</li>
<li>Captures geographical patterns</li>
<li>Example: Forest cover, urban extent</li>
</ul>
<p><strong>Suitable for:</strong></p>
<ul>
<li>Environmental indicators</li>
<li>Land use patterns</li>
<li>Geographic features</li>
<li>Area-based metrics</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Population-Weighted Embeddings:</strong></p>
<ul>
<li>Same features, different weights</li>
<li>Pixels weighted by population density</li>
<li>Emphasizes populated areas</li>
<li>Captures human activity patterns</li>
</ul>
<p><strong>Suitable for:</strong></p>
<ul>
<li>Service delivery indicators</li>
<li>Human capital metrics</li>
<li>Infrastructure usage</li>
<li>Population-dependent services</li>
</ul>
</div></div>
</section>
<section id="overall-performance-comparison" class="slide level2 smaller">
<h2>Overall Performance Comparison</h2>
<p><strong>Aggregate Results (20 Variables):</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Metric</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Mean R²</strong></td>
<td>0.121</td>
<td><strong>0.191</strong></td>
<td><strong>+0.070</strong></td>
</tr>
<tr class="even">
<td>Std Dev</td>
<td>0.267</td>
<td>0.275</td>
<td>-</td>
</tr>
<tr class="odd">
<td>Min R²</td>
<td>-0.588</td>
<td>-0.427</td>
<td>-</td>
</tr>
<tr class="even">
<td>Max R²</td>
<td>0.579</td>
<td><strong>0.693</strong></td>
<td>-</td>
</tr>
</tbody>
</table>
<p><strong>Winner Count:</strong></p>
<ul>
<li>Pop-weighted better: <strong>15 variables (75%)</strong></li>
<li>Regular better: 5 variables (25%)</li>
<li>Ties: 0 variables</li>
</ul>
<p><strong>Statistical Test:</strong></p>
<ul>
<li>Paired t-test: <strong>t = 3.014, p = 0.007</strong></li>
<li><strong>Conclusion:</strong> Pop-weighted significantly better (α = 0.05)</li>
</ul>
</section>
<section id="performance-by-category" class="slide level2 smaller">
<h2>Performance by Category</h2>
<p><strong>Average R² by Category:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Category</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Education</strong></td>
<td>-0.036</td>
<td><strong>0.056</strong></td>
<td><strong>+0.091</strong> 🏆</td>
</tr>
<tr class="even">
<td><strong>Basic Utilities</strong></td>
<td>0.244</td>
<td><strong>0.328</strong></td>
<td><strong>+0.083</strong></td>
</tr>
<tr class="odd">
<td><strong>Infrastructure</strong></td>
<td>-0.013</td>
<td><strong>0.043</strong></td>
<td><strong>+0.056</strong></td>
</tr>
<tr class="even">
<td><strong>Institutional</strong></td>
<td>0.161</td>
<td><strong>0.216</strong></td>
<td><strong>+0.055</strong></td>
</tr>
<tr class="odd">
<td><strong>Health</strong></td>
<td>0.324</td>
<td><strong>0.356</strong></td>
<td><strong>+0.032</strong></td>
</tr>
</tbody>
</table>
<p><strong>Key Finding:</strong></p>
<p>Pop-weighted embeddings improve performance <strong>across all 5 categories</strong></p>
<p>Education shows the <strong>largest improvement</strong> (+0.091)</p>
</section>
<section id="top-5-improvements-with-pop-weighted" class="slide level2 smaller">
<h2>Top 5 Improvements with Pop-Weighted</h2>
<p><strong>Biggest Performance Gains:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular R²</th>
<th>Pop-Weighted R²</th>
<th>Improvement</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>School Dropout (Female)</strong></td>
<td>-0.588</td>
<td>-0.203</td>
<td><strong>+0.385</strong> 🌟</td>
</tr>
<tr class="even">
<td><strong>Network Coverage</strong></td>
<td>0.306</td>
<td>0.512</td>
<td><strong>+0.205</strong></td>
</tr>
<tr class="odd">
<td><strong>Access to 3 Basic Services</strong></td>
<td>0.499</td>
<td>0.620</td>
<td><strong>+0.121</strong></td>
</tr>
<tr class="even">
<td><strong>Public Investment per Capita</strong></td>
<td>0.046</td>
<td>0.167</td>
<td><strong>+0.121</strong></td>
</tr>
<tr class="odd">
<td><strong>Institutional Childbirth</strong></td>
<td>0.579</td>
<td>0.693</td>
<td><strong>+0.114</strong></td>
</tr>
</tbody>
</table>
<p><strong>Interpretation:</strong></p>
<ul>
<li>Female dropout: Massive gain from unpredictable to moderate</li>
<li>Services strongly tied to population: Large improvements</li>
<li>Already good predictors: Get even better</li>
</ul>
</section>
<section id="best-predicted-variables" class="slide level2 smaller">
<h2>Best Predicted Variables</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Regular Embeddings (Top 5):</strong></p>
<ol type="1">
<li>Institutional Childbirth: <strong>R² = 0.579</strong></li>
<li>Access to 3 Basic Services: <strong>R² = 0.499</strong></li>
<li>Tuberculosis Incidence: <strong>R² = 0.368</strong></li>
<li>Civil Registry Coverage: <strong>R² = 0.362</strong></li>
<li>Electricity Coverage: <strong>R² = 0.361</strong></li>
</ol>
<p><strong>Pattern:</strong> Health and basic utilities dominate</p>
</div><div class="column" style="width:50%;">
<p><strong>Pop-Weighted Embeddings (Top 5):</strong></p>
<ol type="1">
<li>Institutional Childbirth: <strong>R² = 0.693</strong> ⭐</li>
<li>Access to 3 Basic Services: <strong>R² = 0.620</strong> ⭐</li>
<li>Network Coverage: <strong>R² = 0.512</strong> ⭐</li>
<li>Electricity Coverage: <strong>R² = 0.466</strong></li>
<li>Civil Registry Coverage: <strong>R² = 0.428</strong></li>
</ol>
<p><strong>Pattern:</strong> Same top variables, <strong>higher accuracy</strong></p>
</div></div>
</section>
<section id="education-category-largest-gains" class="slide level2 smaller">
<h2>Education Category: Largest Gains</h2>
<p><strong>Education Indicators:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>School Dropout (Female)</td>
<td>-0.588</td>
<td>-0.203</td>
<td><strong>+0.385</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>School Dropout (Male)</td>
<td>0.098</td>
<td>0.165</td>
<td><strong>+0.067</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Schools with Tech Floors</td>
<td>0.106</td>
<td>0.220</td>
<td><strong>+0.114</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Computers Delivered</td>
<td>-0.032</td>
<td>-0.018</td>
<td><strong>+0.014</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Qualified Teachers (Initial)</td>
<td>0.078</td>
<td>0.084</td>
<td><strong>+0.006</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Qualified Teachers (Secondary)</td>
<td>0.125</td>
<td>0.086</td>
<td>-0.039</td>
<td>✗</td>
</tr>
</tbody>
</table>
<p><strong>Category Average:</strong> -0.036 → 0.056 (<strong>Δ = +0.091</strong>)</p>
<p><strong>Why education benefits most:</strong></p>
<ul>
<li>Schools located where children live</li>
<li>Technology follows population centers</li>
<li>Dropout rates tied to community factors</li>
</ul>
</section>
<section id="health-category-performance" class="slide level2 smaller">
<h2>Health Category Performance</h2>
<p><strong>Health Indicators:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Institutional Childbirth</td>
<td>0.579</td>
<td><strong>0.693</strong></td>
<td><strong>+0.114</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Tuberculosis Incidence</td>
<td>0.368</td>
<td>0.370</td>
<td>+0.002</td>
<td>✓</td>
</tr>
<tr class="odd">
<td>HIV Incidence</td>
<td>0.024</td>
<td>0.006</td>
<td>-0.019</td>
<td>✗</td>
</tr>
</tbody>
</table>
<p><strong>Category Average:</strong> 0.324 → 0.356 (<strong>Δ = +0.032</strong>)</p>
<p><strong>Insights:</strong></p>
<ul>
<li><strong>Institutional childbirth:</strong> Best overall predictor
<ul>
<li>Hospitals located in population centers</li>
<li>Access improves with population density</li>
</ul></li>
<li><strong>TB incidence:</strong> Minimal difference
<ul>
<li>Disease transmission complex, not just population</li>
</ul></li>
<li><strong>HIV incidence:</strong> Slight decrease
<ul>
<li>Transmission patterns differ from population density</li>
</ul></li>
</ul>
</section>
<section id="infrastructure-category" class="slide level2 smaller">
<h2>Infrastructure Category</h2>
<p><strong>Infrastructure Indicators:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Network Coverage</td>
<td>0.306</td>
<td><strong>0.512</strong></td>
<td><strong>+0.205</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Roads/Railways</td>
<td>-0.001</td>
<td>0.045</td>
<td><strong>+0.046</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Mass Transit Seats</td>
<td>-0.346</td>
<td>-0.427</td>
<td>-0.081</td>
<td>✗</td>
</tr>
</tbody>
</table>
<p><strong>Category Average:</strong> -0.013 → 0.043 (<strong>Δ = +0.056</strong>)</p>
<p><strong>Why the large improvement:</strong></p>
<ul>
<li><strong>Network coverage:</strong> Second-largest gain overall
<ul>
<li>Telecom infrastructure follows population</li>
<li>Cell towers where people live</li>
</ul></li>
<li><strong>Roads/railways:</strong> Modest improvement
<ul>
<li>Infrastructure connects populations</li>
</ul></li>
<li><strong>Mass transit:</strong> Both perform poorly
<ul>
<li>Complex urban planning variable</li>
</ul></li>
</ul>
</section>
<section id="basic-utilities-category" class="slide level2 smaller">
<h2>Basic Utilities Category</h2>
<p><strong>Basic Utilities Indicators:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Access to 3 Basic Services</td>
<td>0.499</td>
<td><strong>0.620</strong></td>
<td><strong>+0.121</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Electricity Coverage</td>
<td>0.361</td>
<td>0.466</td>
<td><strong>+0.105</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Drinking Water Coverage</td>
<td>0.167</td>
<td>0.279</td>
<td><strong>+0.112</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Sanitation Coverage</td>
<td>0.169</td>
<td>0.274</td>
<td><strong>+0.105</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Wastewater Treatment</td>
<td>0.025</td>
<td>-0.001</td>
<td>-0.025</td>
<td>✗</td>
</tr>
</tbody>
</table>
<p><strong>Category Average:</strong> 0.244 → 0.328 (<strong>Δ = +0.083</strong>)</p>
<p><strong>Pattern:</strong></p>
<ul>
<li><strong>Service delivery:</strong> All improve (water, electricity, sanitation)</li>
<li>Services provided where people live</li>
<li><strong>Wastewater:</strong> Environmental, not population-specific</li>
</ul>
</section>
<section id="institutional-category" class="slide level2 smaller">
<h2>Institutional Category</h2>
<p><strong>Institutional Indicators:</strong></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Status</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Public Investment per Capita</td>
<td>0.046</td>
<td>0.167</td>
<td><strong>+0.121</strong></td>
<td>✓</td>
</tr>
<tr class="even">
<td>Civil Registry Coverage</td>
<td>0.362</td>
<td>0.428</td>
<td><strong>+0.066</strong></td>
<td>✓</td>
</tr>
<tr class="odd">
<td>Budget Execution Capacity</td>
<td>0.074</td>
<td>0.052</td>
<td>-0.022</td>
<td>✗</td>
</tr>
</tbody>
</table>
<p><strong>Category Average:</strong> 0.161 → 0.216 (<strong>Δ = +0.055</strong>)</p>
<p><strong>Insights:</strong></p>
<ul>
<li><strong>Public investment:</strong> Large improvement
<ul>
<li>Resources allocated to population centers</li>
</ul></li>
<li><strong>Civil registry:</strong> Moderate improvement
<ul>
<li>Administrative services follow population</li>
</ul></li>
<li><strong>Budget execution:</strong> Slight decrease
<ul>
<li>Institutional efficiency, not spatial</li>
</ul></li>
</ul>
</section>
<section id="where-regular-is-better-5-variables" class="slide level2 smaller">
<h2>Where Regular Is Better (5 Variables)</h2>
<p><strong>Variables favoring regular embeddings:</strong></p>
<table class="caption-top">
<colgroup>
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 25%">
<col style="width: 21%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Indicator</th>
<th>Regular</th>
<th>Pop-Weighted</th>
<th>Difference</th>
<th>Category</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mass Transit Seats</td>
<td>-0.346</td>
<td>-0.427</td>
<td><strong>-0.081</strong></td>
<td>Infrastructure</td>
</tr>
<tr class="even">
<td>Qualified Teachers (Secondary)</td>
<td>0.125</td>
<td>0.086</td>
<td><strong>-0.039</strong></td>
<td>Education</td>
</tr>
<tr class="odd">
<td>Wastewater Treatment</td>
<td>0.025</td>
<td>-0.001</td>
<td><strong>-0.025</strong></td>
<td>Utilities</td>
</tr>
<tr class="even">
<td>Budget Execution Capacity</td>
<td>0.074</td>
<td>0.052</td>
<td><strong>-0.022</strong></td>
<td>Institutional</td>
</tr>
<tr class="odd">
<td>HIV Incidence</td>
<td>0.024</td>
<td>0.006</td>
<td><strong>-0.019</strong></td>
<td>Health</td>
</tr>
</tbody>
</table>
<p><strong>Common Pattern:</strong></p>
<ul>
<li>Environmental variables (wastewater)</li>
<li>Complex institutional metrics (budget execution)</li>
<li>Specialized health transmission (HIV)</li>
<li>Urban planning complexity (mass transit)</li>
<li><strong>Note:</strong> Differences are small compared to improvements elsewhere</li>
</ul>
</section>
<section id="visualization-main-results" class="slide level2 smaller">
<h2>Visualization: Main Results</h2>

<img data-src="../output/rf_embeddings_comparison.png" style="width:100.0%" class="r-stretch"><p><strong>Four panels showing:</strong></p>
<ol type="1">
<li>Top left: Side-by-side R² comparison</li>
<li>Top right: Difference plot (green = improvement)</li>
<li>Bottom left: Category averages</li>
<li>Bottom right: R² distribution</li>
</ol>
</section>
<section id="statistical-significance" class="slide level2 smaller">
<h2>Statistical Significance</h2>
<p><strong>Paired t-test (Pop-weighted vs Regular):</strong></p>
<ul>
<li><strong>Null hypothesis:</strong> No difference in mean R² between methods</li>
<li><strong>Alternative hypothesis:</strong> Pop-weighted has higher mean R²</li>
</ul>
<p><strong>Results:</strong></p>
<ul>
<li><strong>Mean difference:</strong> +0.070</li>
<li><strong>t-statistic:</strong> 3.014</li>
<li><strong>p-value:</strong> 0.007</li>
<li><strong>Degrees of freedom:</strong> 19 (20 paired observations)</li>
</ul>
<p><strong>Conclusion:</strong></p>
<p>We <strong>reject the null hypothesis</strong> at α = 0.05</p>
<p>Pop-weighted embeddings are <strong>statistically significantly better</strong> than regular embeddings</p>
<p><strong>Effect size:</strong> Medium to large (Cohen’s d ≈ 0.67)</p>
</section>
<section id="why-pop-weighted-performs-better" class="slide level2 smaller">
<h2>Why Pop-Weighted Performs Better</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Theoretical Reasons:</strong></p>
<ol type="1">
<li><strong>Service delivery follows population</strong>
<ul>
<li>Schools where children live</li>
<li>Hospitals in populated areas</li>
<li>Utilities serve people</li>
</ul></li>
<li><strong>Reduces rural/urban bias</strong>
<ul>
<li>Regular: Overweights empty areas</li>
<li>Pop-weighted: Focuses on inhabited areas</li>
</ul></li>
<li><strong>Aligns with policy targets</strong>
<ul>
<li>Services aim to reach people</li>
<li>Coverage measured by population</li>
</ul></li>
</ol>
</div><div class="column" style="width:50%;">
<p><strong>Empirical Evidence:</strong></p>
<ul>
<li><strong>15/20 variables</strong> improve</li>
<li><strong>All 5 categories</strong> show gains</li>
<li><strong>Largest gains</strong> in service-related variables</li>
</ul>
<p><strong>When it matters most:</strong></p>
<ul>
<li>Education: +0.091 average</li>
<li>Infrastructure: +0.056 average</li>
<li>Basic utilities: +0.083 average</li>
</ul>
<p><strong>When it matters less:</strong></p>
<ul>
<li>Environmental indicators</li>
<li>Institutional capacity</li>
<li>Specialized health metrics</li>
</ul>
</div></div>
</section>
<section id="implications-for-researchers" class="slide level2 smaller">
<h2>Implications for Researchers</h2>
<p><strong>Recommendation:</strong> Use population-weighted embeddings for service-related predictions</p>
<p><strong>Guidelines:</strong></p>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Use Pop-Weighted for:</strong></p>
<ul>
<li>Education indicators</li>
<li>Health service coverage</li>
<li>Infrastructure (networks, roads)</li>
<li>Basic utilities (water, electricity)</li>
<li>Public investment allocation</li>
<li>Service delivery metrics</li>
</ul>
<p><strong>Expected improvement:</strong> Δ R² = +0.05 to +0.20</p>
</div><div class="column" style="width:50%;">
<p><strong>Use Regular for:</strong></p>
<ul>
<li>Environmental variables</li>
<li>Land use patterns</li>
<li>Geographic features</li>
<li>Institutional capacity</li>
<li>Non-spatial metrics</li>
</ul>
<p><strong>Expected improvement:</strong> Minimal or negative</p>
<p><strong>Hybrid Approach:</strong></p>
<ul>
<li>Test both methods</li>
<li>Select best for each variable</li>
<li>Ensemble predictions</li>
</ul>
</div></div>
</section>
<section id="implications-for-policymakers" class="slide level2 smaller">
<h2>Implications for Policymakers</h2>
<p><strong>For Resource Allocation:</strong></p>
<ol type="1">
<li><strong>Satellite data CAN predict service gaps</strong>
<ul>
<li>Institutional childbirth: R² = 0.69</li>
<li>Access to basic services: R² = 0.62</li>
<li>Network coverage: R² = 0.51</li>
</ul></li>
<li><strong>Population weighting improves targeting</strong>
<ul>
<li>Better identifies underserved populations</li>
<li>Aligns with where people actually live</li>
</ul></li>
<li><strong>Data-driven policy possible</strong>
<ul>
<li>Monitor service coverage remotely</li>
<li>Identify intervention priorities</li>
<li>Track progress over time</li>
</ul></li>
</ol>
<p><strong>For Service Planning:</strong></p>
<ul>
<li>Education: Focus on population centers (large improvements)</li>
<li>Infrastructure: Network coverage highly predictable</li>
<li>Utilities: Basic services can be well-estimated</li>
</ul>
</section>
<section id="limitations" class="slide level2 smaller">
<h2>Limitations</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Data Limitations:</strong></p>
<ul>
<li>Single year (2017) satellite data</li>
<li>Population weights from census</li>
<li>Temporal lag between image and services</li>
<li>Missing variables not tested</li>
</ul>
<p><strong>Model Limitations:</strong></p>
<ul>
<li>Random Forest only (one algorithm)</li>
<li>Standard hyperparameters</li>
<li>No feature selection</li>
<li>No spatial cross-validation</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Context Limitations:</strong></p>
<ul>
<li>Bolivia-specific results</li>
<li>Municipal-level aggregation</li>
<li>May not generalize to:
<ul>
<li>Other countries</li>
<li>Different contexts</li>
<li>Sub-municipal scales</li>
</ul></li>
</ul>
<p><strong>Interpretation Cautions:</strong></p>
<ul>
<li>Correlation, not causation</li>
<li>Satellite captures proxies</li>
<li>Service quality vs.&nbsp;coverage</li>
<li>Equity considerations</li>
</ul>
</div></div>
</section>
<section id="future-research-directions" class="slide level2 smaller">
<h2>Future Research Directions</h2>
<p><strong>Methodological Extensions:</strong></p>
<ol type="1">
<li><strong>Algorithm comparison</strong>
<ul>
<li>XGBoost, Neural Networks</li>
<li>Ensemble methods</li>
<li>Deep learning on raw images</li>
</ul></li>
<li><strong>Temporal analysis</strong>
<ul>
<li>Multiple years (2012-2020)</li>
<li>Change detection</li>
<li>Trend prediction</li>
</ul></li>
<li><strong>Spatial methods</strong>
<ul>
<li>Spatial cross-validation</li>
<li>Geographic weighting</li>
<li>Spatial autocorrelation</li>
</ul></li>
</ol>
<p><strong>Variable Extensions:</strong></p>
<ol start="4" type="1">
<li><strong>More service indicators</strong>
<ul>
<li>Additional SDG variables</li>
<li>Quality metrics (not just coverage)</li>
<li>Service efficiency</li>
</ul></li>
<li><strong>Multi-source data</strong>
<ul>
<li>Combine with other datasets</li>
<li>Night-time lights</li>
<li>Mobile phone data</li>
</ul></li>
</ol>
</section>
<section id="comparison-with-previous-study" class="slide level2 smaller">
<h2>Comparison with Previous Study</h2>
<p><strong>Previous Analysis (Regular Embeddings Only):</strong></p>
<ul>
<li>Best: Institutional Childbirth (R² = 0.579)</li>
<li>Worst: School Dropout Female (R² = -0.588)</li>
<li>Mean: R² = 0.121</li>
</ul>
<p><strong>Current Analysis (Pop-Weighted):</strong></p>
<ul>
<li>Best: Institutional Childbirth (R² = <strong>0.693</strong>) ⬆</li>
<li>Improved: School Dropout Female (R² = <strong>-0.203</strong>) ⬆</li>
<li>Mean: R² = <strong>0.191</strong> ⬆</li>
</ul>
<p><strong>Key Improvements:</strong></p>
<ul>
<li>Same best variable, <strong>20% better</strong> prediction</li>
<li>Worst variable <strong>65% better</strong> (still poor, but improving)</li>
<li>Overall mean <strong>58% higher</strong></li>
</ul>
<p><strong>Consistency:</strong> Top variables remain the same, accuracy increases</p>
</section>
<section id="practical-recommendations" class="slide level2 smaller">
<h2>Practical Recommendations</h2>
<p><strong>For Data Scientists:</strong></p>
<ol type="1">
<li><strong>Default choice:</strong> Pop-weighted for service predictions</li>
<li><strong>Test both:</strong> When in doubt, compare methods</li>
<li><strong>Category-specific:</strong> Education and utilities benefit most</li>
<li><strong>Report both:</strong> For transparency and comparison</li>
</ol>
<p><strong>For Policy Analysts:</strong></p>
<ol type="1">
<li><strong>Trust the predictions:</strong> High R² variables (&gt;0.5) are reliable</li>
<li><strong>Use with caution:</strong> Low R² variables (&lt;0.2) need ground data</li>
<li><strong>Population matters:</strong> Weight by population for service metrics</li>
<li><strong>Remote monitoring:</strong> Satellite data enables cost-effective tracking</li>
</ol>
<p><strong>For Development Organizations:</strong></p>
<ol type="1">
<li><strong>Targeting:</strong> Use predictions to identify underserved areas</li>
<li><strong>Monitoring:</strong> Track service coverage changes over time</li>
<li><strong>Planning:</strong> Predict service needs in data-scarce regions</li>
<li><strong>Evaluation:</strong> Assess intervention impacts with satellite data</li>
</ol>
</section>
<section id="key-takeaways" class="slide level2 smaller">
<h2>Key Takeaways</h2>
<p><strong>Main Findings:</strong></p>
<ol type="1">
<li><strong>Pop-weighted embeddings significantly better</strong> (p = 0.007)
<ul>
<li>75% of variables improve</li>
<li>Mean R² increases from 0.121 to 0.191 (+58%)</li>
</ul></li>
<li><strong>Consistent across categories</strong>
<ul>
<li>All 5 categories show improvements</li>
<li>Education benefits most (+0.091)</li>
</ul></li>
<li><strong>Largest improvements in service delivery</strong>
<ul>
<li>School dropout (female): +0.385</li>
<li>Network coverage: +0.205</li>
<li>Access to basic services: +0.121</li>
</ul></li>
<li><strong>Best predictions remain strong</strong>
<ul>
<li>Institutional childbirth: R² = 0.693</li>
<li>Access to 3 basic services: R² = 0.620</li>
</ul></li>
</ol>
<p><strong>Bottom Line:</strong> <strong>Account for population distribution when predicting service-related outcomes</strong></p>
</section>
<section id="data-and-reproducibility" class="slide level2 smaller">
<h2>Data and Reproducibility</h2>
<div class="columns">
<div class="column" style="width:50%;">
<p><strong>Data Sources:</strong></p>
<ul>
<li>SDG Variables: 339 municipalities, 65 indicators</li>
<li>Regular embeddings: 64 features</li>
<li>Pop-weighted embeddings: 64 features</li>
<li>GitHub repository: <a href="https://github.com/quarcs-lab/ds4bolivia">ds4bolivia</a></li>
</ul>
<p><strong>Software:</strong></p>
<ul>
<li>Python 3.10</li>
<li>scikit-learn (Random Forest)</li>
<li>pandas, numpy, matplotlib</li>
<li>scipy (statistical tests)</li>
</ul>
</div><div class="column" style="width:50%;">
<p><strong>Code:</strong></p>
<ul>
<li>Script: <code>code/04_rf_public_services_comparison.py</code></li>
<li>Fully reproducible with random seed</li>
<li>Streams data directly from GitHub</li>
</ul>
<p><strong>Outputs:</strong></p>
<ul>
<li>Figure: <code>output/rf_embeddings_comparison.png</code></li>
<li>Results: <code>output/rf_embeddings_comparison.csv</code></li>
<li>Details: <code>output/rf_embeddings_comparison_detailed.csv</code></li>
</ul>
<p><strong>Project:</strong> claude4data</p>
</div></div>
</section>
<section class="slide level2">

<p><strong>Contact:</strong></p>
<p>Carlos Mendez</p>
<p><strong>Project:</strong> claude4data</p>
<p>🛠️ Generated with <a href="https://claude.com/claude-code">Claude Code</a></p>

</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="embeddings_comparison_slides_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': true,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>